apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledgerwriter
  namespace: ledgerwriter
spec:
  selector:
    matchLabels:
      app: ledgerwriter
  template: 
    spec: 
      containers:
      - name: ledgerwriter
        image: gcr.io/bnb-dev-363714/bnb-bank/release/ledgerwriter:0f544b5
        env:
        - name: ENABLE_TRACING
          value: "true"
        - name: ENABLE_METRICS
          value: "true"
        - name: LOG_LEVEL
          value: "info"