apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  template: 
    spec: 
      containers:
      - name: loadgenerator
        image: gcr.io/bnb-dev-363714/bnb-bank/release/loadgenerator:e30e34b
        env:
        - name: LOG_LEVEL
          value: "info"